"""secfix CLI — the entry point invoked by CI after the security scan.

Pipeline:
  load reports -> normalize -> policy filter -> generate fixes -> apply ->
  validate (tests + residue re-check) -> (optionally) branch/commit/push + open PR.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import os
import sys
from typing import List

from . import __version__
from .fixers import Patch
from .fixers.code import fix_code_finding
from .fixers.deps import apply_dependency_fixes
from .models import Finding
from .scanners.gather import collect_findings
from . import validate as _validate
from . import git_ops, github_pr, gitlab_mr


def _severity_ok(f: Finding, allowed: List[str]) -> bool:
    return f.severity.lower() in allowed


def _apply(root: str, patch: Patch) -> None:
    for rel, content in patch.files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)


def _build_pr_body(fixed: List[Patch], escalated: List[Finding], validation: str) -> str:
    lines = ["## 🔒 Automated security fixes", ""]
    lines.append("This PR was generated by **secfix** after the CI security scan found vulnerabilities.")
    lines.append("")
    lines.append("### Fixed")
    for p in fixed:
        extra = getattr(p, "extra_findings", None)
        if extra:
            for f in extra:
                lines.append(f"- **{f.cve}** ({f.severity}) — bump `{f.component}` "
                             f"`{f.current_version}` → `{f.fixed_version}` _(Black Duck)_")
        else:
            f = p.finding
            src = "Fortify" if f.scanner == "fortify" else f.scanner
            lines.append(f"- **{f.category or f.cve}** ({f.severity}) in `{f.file or p.touched()[0]}` "
                         f"_( {src} · provider: {p.provider} )_")
    if escalated:
        lines.append("")
        lines.append("### ⚠️ Needs human attention (not auto-fixed)")
        for f in escalated:
            lines.append(f"- **{f.title}** ({f.severity}) — `{f.file or f.component}`")
    lines.append("")
    lines.append("### Validation")
    lines.append("```")
    lines.append(validation.strip() or "(none)")
    lines.append("```")
    lines.append("")
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    lines.append(f"_Generated by secfix v{__version__} · {stamp}_")
    return "\n".join(lines)


def run(argv: List[str]) -> int:
    ap = argparse.ArgumentParser(prog="secfix", description="CI security auto-fix agent")
    ap.add_argument("--root", default=".", help="repository root to operate on")
    ap.add_argument("--blackduck", help="path to Black Duck report JSON (file mode)")
    ap.add_argument("--fortify", help="path to Fortify report JSON (file mode)")
    # --- live API mode (Black Duck) ---
    ap.add_argument("--blackduck-url", default="", help="Black Duck base URL (live mode; token via $BD_API_TOKEN)")
    ap.add_argument("--blackduck-project", default="", help="Black Duck project name (live mode)")
    ap.add_argument("--blackduck-version", default="main", help="Black Duck version name (live mode)")
    # --- live API mode (Fortify SSC) ---
    ap.add_argument("--fortify-url", default="", help="Fortify SSC base URL (live mode; token via $FORTIFY_TOKEN)")
    ap.add_argument("--fortify-app", default="", help="Fortify application name (live mode)")
    ap.add_argument("--fortify-version", default="main", help="Fortify application version (live mode)")
    ap.add_argument("--req", default="requirements.txt", help="requirements file path (relative to root)")
    ap.add_argument("--severities", default="critical,high,medium",
                    help="comma list of severities to auto-fix")
    ap.add_argument("--test-cmd", default="", help="validation test command, e.g. 'py -m unittest discover'")
    ap.add_argument("--base", default="main", help="base/target branch for the PR/MR")
    ap.add_argument("--branch", default="", help="head/source branch name (default auto)")
    ap.add_argument("--repo", default=os.getenv("GITHUB_REPOSITORY", ""), help="GitHub owner/name")
    ap.add_argument("--provider", choices=["auto", "github", "gitlab"], default="auto",
                    help="where to publish (auto-detected from CI env by default)")
    ap.add_argument("--project", default="",
                    help="GitLab project id or 'group/name' (defaults to $CI_PROJECT_ID)")
    ap.add_argument("--gitlab-url", default="",
                    help="GitLab base URL, e.g. https://gitlab.com (defaults to $CI_SERVER_URL)")
    ap.add_argument("--open-pr", action="store_true", help="commit, push and open a PR/MR")
    ap.add_argument("--pr-body-out", default="", help="write the PR body markdown to this path")
    ap.add_argument("--fail-on-findings", action="store_true",
                    help="exit non-zero if actionable findings were present")
    args = ap.parse_args(argv)

    allowed = [s.strip().lower() for s in args.severities.split(",") if s.strip()]
    findings = collect_findings(args)
    actionable = [f for f in findings if _severity_ok(f, allowed)]
    actionable.sort(key=lambda f: f.severity_rank())

    print(f"secfix v{__version__}: {len(findings)} findings, "
          f"{len(actionable)} within severities {allowed}")

    fixed: List[Patch] = []
    escalated: List[Finding] = []

    # --- SCA: one grouped requirements bump ---
    dep_patch = apply_dependency_fixes(args.root, actionable, req_file=args.req)
    bumped_components = set()
    if dep_patch:
        _apply(args.root, dep_patch)
        fixed.append(dep_patch)
        for f in getattr(dep_patch, "extra_findings", []):
            bumped_components.add((f.component or "").lower())
            print(f"  [deps] {f.component} {f.current_version} -> {f.fixed_version} ({f.cve})")
    # dependency findings we could not bump (transitive / not in manifest / no fix) -> escalate
    for f in actionable:
        if f.type == "dependency_vuln" and (f.component or "").lower() not in bumped_components:
            escalated.append(f)
            reason = "no fixed version" if not f.fixed_version else "not a direct dependency"
            print(f"  [escalate] {f.component} {f.cve} ({reason})")

    # --- SAST: per-finding code fix ---
    for f in actionable:
        if f.type != "code_vuln":
            continue
        patch = fix_code_finding(args.root, f)
        if patch:
            _apply(args.root, patch)
            fixed.append(patch)
            print(f"  [{patch.provider}] fixed {f.category} in {f.file}")
        else:
            escalated.append(f)
            print(f"  [escalate] {f.category} in {f.file} (no verified fix)")

    # --- Validation ---
    val_lines: List[str] = []
    if args.test_cmd:
        ok, out = _validate.run_tests(args.root, args.test_cmd.split())
        val_lines.append(f"tests: {'PASS' if ok else 'FAIL'} ({args.test_cmd})")
        if not ok:
            print("Validation FAILED — tests did not pass:\n" + out)
            return 3
    # residue / presence checks
    for p in fixed:
        for f in getattr(p, "extra_findings", [p.finding]):
            if f.type == "dependency_vuln":
                good = _validate.verify_dependency(args.root, f, req_file=args.req)
            else:
                good = _validate.verify_code(args.root, f)
            val_lines.append(f"{'OK ' if good else 'BAD'} {f.label()}")
    validation = "\n".join(val_lines)
    print(validation)

    pr_body = _build_pr_body(fixed, escalated, validation)
    if args.pr_body_out:
        with open(args.pr_body_out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(pr_body)
        print(f"PR body written to {args.pr_body_out}")

    # --- Publish ---
    if args.open_pr and fixed:
        provider = args.provider
        if provider == "auto":
            provider = "gitlab" if (os.getenv("GITLAB_CI") or os.getenv("CI_SERVER_URL")) else "github"
        branch = args.branch or f"secfix/auto-{_dt.datetime.now().strftime('%Y%m%d-%H%M%S')}"
        title = f"[Security] Automated fixes for {len(fixed)} finding group(s)"
        labels = ["security", "automated"]

        if provider == "gitlab":
            token = os.getenv("GITLAB_TOKEN", "")
            project = args.project or os.getenv("CI_PROJECT_ID", "")
            base_url = args.gitlab_url or os.getenv("CI_SERVER_URL", "https://gitlab.com")
            api_url = os.getenv("CI_API_V4_URL") or base_url.rstrip("/") + "/api/v4"
            if not token or not project:
                print("ERROR: gitlab publish requires GITLAB_TOKEN and --project/$CI_PROJECT_ID",
                      file=sys.stderr)
                return 4
            git_ops.create_branch_and_commit(args.root, branch, title)
            git_ops.push(args.root, branch)
            mr = gitlab_mr.open_merge_request(project, branch, args.base, title, pr_body,
                                              token, labels, api_url=api_url)
            print(f"Opened MR !{mr.get('iid')}: {mr.get('web_url')}")
        else:
            token = os.getenv("GITHUB_TOKEN", "")
            if not token or not args.repo:
                print("ERROR: github publish requires GITHUB_TOKEN and --repo/GITHUB_REPOSITORY",
                      file=sys.stderr)
                return 4
            api_url = os.getenv("GITHUB_API_URL", "https://api.github.com")
            git_ops.create_branch_and_commit(args.root, branch, title)
            git_ops.push(args.root, branch)
            pr = github_pr.open_pull_request(args.repo, args.base, branch, title, pr_body,
                                             token, labels, api_url=api_url)
            print(f"Opened PR #{pr.get('number')}: {pr.get('html_url')}")

    if args.fail_on_findings and actionable:
        return 2
    return 0


def main() -> None:
    raise SystemExit(run(sys.argv[1:]))


if __name__ == "__main__":
    main()
